from marshmallow import Schema
from webargs import fields


class TagSchema(Schema):
    icon = fields.Str(example="fas-star", allow_none=True)
    text = fields.Str(example="Chef Featured", allow_none=True)


class ItemSchema(Schema):
    _id = fields.Str(required=True, example="da95f757-603a-41a8-aa62-dede4484a601")
    image = fields.Url(
        example="https://via.placeholder.com/150", allow_none=True, missing=None
    )
    name = fields.Str(example="Meatball Pasta", allow_none=True)
    price = fields.Str(example="$6.99", allow_none=True)
    tags = fields.List(fields.Nested(TagSchema))
    sections = fields.List(fields.Str(), example=["A la carte", "Chef's Featured"])
    description = fields.Str(example="A Pasta with Meatballs", allow_none=True)


class SectionSchema(Schema):
    _id = fields.Str(required=True, example="da95f757-603a-41a8-aa62-dede4484a601")
    name = fields.Str(
        description="Name of section", example="A la carte", allow_none=True
    )
    menu_items = fields.List(fields.Nested(ItemSchema))
    description = fields.Str(
        description="Name of section", example="Piece by piece", allow_none=True
    )
    subtitle = fields.Str(description="Headers for section anchors", allow_none=True)


class MenuSchema(Schema):
    name = fields.Str(description="Name of the restaurants", example="Hollywood Cafe")
    sections = fields.List(fields.Nested(SectionSchema, required=True))


class GetRestaurantSchema(Schema):
    name = fields.Str(description="Name of the restaurants", example="Hollywood Cafe")
    image = fields.Url(example="https://via.placeholder.com/150")
    description = fields.Str(example="A cafe in Hollywood")
    enable_trace = fields.Bool(
        description="Enable contact tracing functionality for the restaurants"
    )
    force_trace = fields.Bool(
        description="Force show the contact tracing popup when the user visits the menu app."
    )
    tracing_key = fields.Str(description="Tracing key generated by tracing.pickeasy.ca")
    menus = fields.List(fields.Str())


class RestaurantSchema(Schema):
    slug = fields.Str(
        description="Slug of the menu", example="hollywood", required=True
    )
    name = fields.Str(
        description="Name of the restaurants", example="Hollywood Cafe", allow_none=True
    )
    image = fields.Url(example="https://via.placeholder.com/150", allow_none=True)
    description = fields.Str(example="A cafe in Hollywood", allow_none=True)


class PaginationMenuSchema(Schema):
    name = fields.Str(description="Name of the restaurants", example="Hollywood Cafe")
    slug = fields.Str()


pagination_args = {
    "page": fields.Int(description="Page number of table", default=1),
    "limit": fields.Int(description="How many entries per page", default=5),
}

qr_args = {"url": fields.Str(description="url of website to be encoded")}

file_args = {"file": fields.Field()}
