from marshmallow import Schema
from webargs import fields


class TagV2Schema(Schema):
    icon = fields.Str(example="fas-star", allow_none=True)
    text = fields.Str(example="Chef Featured", allow_none=True)
    background_color = fields.Str(example="black", allow_none=True)


class ItemV2Schema(Schema):
    _id = fields.Str(example="da95f757-603a-41a8-aa62-dede4484a601")
    image = fields.Url(
        example="https://via.placeholder.com/150", allow_none=True, missing=None
    )
    name = fields.Str(example="Meatball Pasta", allow_none=True)
    price = fields.Str(example="$6.99", allow_none=True)
    tags = fields.List(fields.Nested(TagV2Schema))
    description = fields.Str(example="A Pasta with Meatballs", allow_none=True)


class SectionV2Schema(Schema):
    _id = fields.Str(example="da95f757-603a-41a8-aa62-dede4484a601")
    name = fields.Str(
        description="Name of section", example="A la carte", allow_none=True
    )
    menu_items = fields.List(fields.Nested(ItemV2Schema))
    description = fields.Str(
        description="Name of section", example="Piece by piece", allow_none=True
    )
    subtitle = fields.Str(description="Headers for section anchors", allow_none=True)


class MenuV2Schema(Schema):
    name = fields.Str(description="Name of the menu", example="lunch", required=True)
    sections = fields.List(fields.Nested(SectionV2Schema, required=True))
    start = fields.Int(
        description="Start time for menu interval in the form of total seconds elapsed from 12:00 am",
        example=46500,
    )
    end = fields.Int(
        description="End time for menu interval in the form of total seconds elapsed from 12:00 am",
        example=51000,
    )
    footnote = fields.Str(
        description="footnote at bottom of page", example="All items are peanut free"
    )


class EditMenuV2Schema(Schema):
    name = fields.Str(description="Name of the menu", example="lunch")
    sections = fields.List(fields.Nested(SectionV2Schema, required=True))
    start = fields.Int(
        description="Start time for menu interval in the form of total seconds elapsed from 12:00 am",
        example=46500,
    )
    end = fields.Int(
        description="End time for menu interval in the form of total seconds elapsed from 12:00 am",
        example=51000,
    )


class LazyMenuSchema(Schema):
    name = fields.Str(example="Lunch", description="Name of menu")
    start = fields.Int(
        description="Start time for menu interval in the form of total seconds elapsed from 12:00 am",
        example=46500,
    )
    end = fields.Int(
        description="End time for menu interval in the form of total seconds elapsed from 12:00 am",
        example=51000,
    )


class BaseRestaurantSchema(Schema):
    name = fields.Str(
        description="Name of the restaurant", example="Hollywood Cafe", allow_none=True
    )
    image = fields.Url(example="https://via.placeholder.com/150", allow_none=True)
    description = fields.Str(example="A cafe in Hollywood", allow_none=True)
    qrcode_link = fields.Url(
        example="https://menu.pickeasy,ca", description="dynamic qrcode link"
    )
    enable_trace = fields.Bool(
        description="Enable contact tracing functionality for the restaurant"
    )
    force_trace = fields.Bool(
        description="Force show the contact tracing popup when the user visits the menu app."
    )
    tracing_key = fields.Str(description="Tracing key generated by tracing.pickeasy.ca")
    public = fields.Bool(allow_none=True)
    can_upload = fields.Bool(allow_none=True)


class RestaurantSchema(BaseRestaurantSchema):
    slug = fields.Str(description="Slug of the menu", example="hollywood")


class GetRestaurantSchema(BaseRestaurantSchema):
    menus = fields.List(fields.Nested(LazyMenuSchema))


class OnboardingSchema(Schema):
    name = fields.Str(
        description="Restaurant name", example="My first restaurant", allow_none=True
    )
    item_price = fields.Str(
        description="Item's price", exmaple="$5.99", allow_none=True
    )
    item_name = fields.Str(description="Item's name", example="Sushi", allow_none=True)
    item_description = fields.Str(
        description="Item's description", example="Raw fish", allow_none=True
    )
    section_name = fields.Str(
        description="Section's description", example="Japanese", allow_none=True
    )
