from typing import Optional

from blueprints.restaurant.documents.menu import Menu
from mongoengine import (
    BooleanField,
    Document,
    ListField,
    ReferenceField,
    StringField,
    URLField,
)


class Restaurant(Document):
    slug = StringField(primary_key=True, required=True)
    """
    url key for this restaurant
    """

    description = StringField()
    """
    description of this restaurant
    """

    image = URLField()
    """
    image url for this restaurant
    """

    menus = ListField(ReferenceField("Menu"), default=[])
    """
    list of menus for this restaurant
    """

    name = StringField()
    """
    name of the restaurant
    """

    force_trace = BooleanField(default=False)
    """
    field to force contact tracing on older menus
    """

    enable_trace = BooleanField(default=False)
    """
    field to enable contact tracing on restaurant
    """

    tracing_key = StringField()
    """
    key for tracing generated by tracing.pickeasy.ca
    """

    def to_dict(self):
        """ serialize restaurant to json"""
        menus = [menu.name for menu in self.menus]
        serialized_restaurant = self.to_mongo().to_dict()
        serialized_restaurant["menus"] = menus
        return serialized_restaurant

    def get_menu(self, name: str) -> Optional[Menu]:
        """ get menu from restaurant """
        for menu in self.menus:
            if menu.name == name:
                return menu
        return None
