name: Run pre-commit for menu-api

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: menu-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Copy config file
        run: |
          cp config.py.bak config.py
      - name: Run pre-commit
        run: |
          FLASK_ENV=testing pre-commit run --verbose --all-files --show-diff-on-failure
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics --max-line-length=120 --ignore=F401,F811,E203,E231
      - name: Run pytest
        run: |
          FLASK_ENV=testing pytest .
